### ISSUE TITLE
Error in test access

### ISSUE THREAD

**Issue by pipeline1987** [PacktPublishing/-Deploying-Jenkins-to-the-Cloud-with-DevOps-Tools#3]
Im running the ansible-playbook ansible/test.yml and then got this error:

TASK [ec2_remote_facts] ****************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "This module has been removed. The module documentation for Ansible-2.7 may contain hints for porting"}

ansible v2.9.1
python v2.7.15+

**Comment by hypery2k** [comment]
sorry for the issue, could you try to replace _ec2_remote_facts_ with _ec2_instance_facts_ here: https://github.com/PacktPublishing/-Deploying-Jenkins-to-the-Cloud-with-DevOps-Tools/blob/63615af85b7f2ae103ed73745e06aa732bfedfb7/Section1_PublicCloud/ansible/test.yml#L12

**Comment by pipeline1987** [comment]
Thank you very much friend it worked 100% Regards!!! 🧙‍♂️
